version: '3.3'

volumes: 
    dbdata: {}

networks: 
    app-network:
        driver: bridge

services:
    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: dockerize -template /.docker/nginx/default.temp.conf:/etc/nginx/conf.d/default.conf nginx
        restart: always
        tty: true
        environment: 
            - APP_NAME=app
            - APP_PORT=9000
        volumes:
            - ./src:/var/www
        ports: 
            - 80:80
        depends_on: 
            - app
        networks:
            - app-network

    app:
        build: .
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s /entrypoint.sh
        volumes:
            - ./src:/var/www
        expose: 
            - 9000
        networks:
            - app-network
        depends_on: 
            - db
            - redis

    db:
        image: mysql:5.7.22
        container_name: db
        command: --innodb-use-native-aio=0
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - app-network

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        expose: 
            - 6379
        networks:
            - app-network